export class IconConstants {
  static readonly NAVIGATION_HOME: string = '\ue7c6'
  static readonly RIGHT: string = '\ue7eb' //右箭头
  static readonly CHOOSE_SCHOOL: string = '\ue831' //选择学校
  static readonly HOME: string = '\ue7c6' //学校
  static readonly USER: string = '\ue7ae' //用户
  static readonly LOCK: string = '\ue7ca' //锁
  static readonly AUTH: string = '\ue823' //认证
  static readonly CLOSE: string = '\ue7ff' //关闭
  static readonly PHONE: string = '\ue621' //手机
  static readonly SAFETY: string = '\ue7c0' //安全
}