export class MessageCountModel {
  total_un_read_count: number = 0
  todo_un_read_count: number = 0
  course_un_read_count: number = 0
  task_un_read_count: number = 0
  announcement_un_read_count: number = 0
  subgroup_un_read_count: number = 0
  discussion_un_read_count: number = 0
  qa_un_read_count: number = 0
  person_un_read_count: number = 0
  system_un_read_count: number = 0
  chat_c2c_un_read_count: number = 0
  chat_group_un_read_count: number = 0
}